#pragma once
#include <netdb.h>
#include <stdio.h>
#include <stdlib.h>
#include <err.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/socket.h>
#include <sys/types.h> 
#include <netinet/in.h>
#include <strings.h>
int server(void);
